"""initial_marketplace_schema

Revision ID: e0160821edd7
Revises: 
Create Date: 2026-09-02 12:58:44.297229
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0160821edd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_algo', sa.String(length=32), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('full_name_te', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'FARMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('language_pref', sa.Enum('EN', 'TE', name='language_pref'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_address_line', sa.String(length=255), nullable=False),
    sa.Column('default_village', sa.String(length=120), nullable=False),
    sa.Column('default_mandal', sa.String(length=120), nullable=False),
    sa.Column('default_district', sa.String(length=120), nullable=False),
    sa.Column('default_pincode', sa.String(length=10), nullable=False),
    sa.Column('default_latitude', sa.Float(), nullable=True),
    sa.Column('default_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position('@' in email) > 1", name='ck_user_email_shape'),
    sa.CheckConstraint('char_length(password_hash) >= 20', name='ck_user_hash_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=False)
    op.create_index('ix_user_role_active', 'user_account', ['role', 'is_active'], unique=False)
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=False),
    sa.Column('after_state', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'admin_audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'admin_audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('advisory_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_te', sa.String(length=200), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_te', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_te', sa.Text(), nullable=False),
    sa.Column('crop_name_en', sa.String(length=120), nullable=False),
    sa.Column('crop_name_te', sa.String(length=120), nullable=False),
    sa.Column('crop_slug', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('season', sa.Enum('KHARIF', 'RABI', 'ZAID', 'ALL_YEAR', name='advisory_season'), nullable=False),
    sa.Column('source_type', sa.Enum('ICAR', 'KVK', 'STATE_AGRI_DEPT', 'OTHER', name='advisory_source'), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=160), nullable=False),
    sa.Column('disclaimer_en', sa.Text(), nullable=False),
    sa.Column('disclaimer_te', sa.Text(), nullable=False),
    sa.Column('hero_image_name', sa.String(length=255), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_advisory_slug')
    )
    op.create_index('ix_advisory_crop_season', 'advisory_entry', ['crop_slug', 'season'], unique=False)
    op.create_index(op.f('ix_advisory_entry_slug'), 'advisory_entry', ['slug'], unique=False)
    op.create_index('ix_advisory_published', 'advisory_entry', ['is_published', 'reviewed_on'], unique=False)
    op.create_table('farmer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('display_name_te', sa.String(length=120), nullable=False),
    sa.Column('bio_en', sa.Text(), nullable=False),
    sa.Column('bio_te', sa.Text(), nullable=False),
    sa.Column('years_farming', sa.Integer(), nullable=False),
    sa.Column('primary_crops', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status'), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('id_document_ref', sa.String(length=255), nullable=False),
    sa.Column('is_local_partner', sa.Boolean(), nullable=False),
    sa.Column('local_partner_since', sa.Date(), nullable=True),
    sa.Column('payout_upi_id', sa.String(length=120), nullable=False),
    sa.Column('payout_account_name', sa.String(length=120), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_farmer_profile_user')
    )
    op.create_index(op.f('ix_farmer_profile_user_id'), 'farmer_profile', ['user_id'], unique=False)
    op.create_index('ix_farmer_verification', 'farmer_profile', ['verification_status', 'is_local_partner'], unique=False)
    op.create_table('mandi_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name_en', sa.String(length=120), nullable=False),
    sa.Column('crop_name_te', sa.String(length=120), nullable=False),
    sa.Column('crop_slug', sa.String(length=120), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('mandi_name', sa.String(length=120), nullable=False),
    sa.Column('mandal', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'QUINTAL', 'TONNE', 'DOZEN', 'BUNDLE', 'CRATE', 'PIECE', name='quantity_unit'), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('modal_price >= 0', name='ck_mandi_modal_nonneg'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_slug', 'mandi_name', 'price_date', name='uq_mandi_crop_day')
    )
    op.create_index('ix_mandi_crop_date', 'mandi_price', ['crop_slug', 'price_date'], unique=False)
    op.create_index('ix_mandi_district', 'mandi_price', ['district'], unique=False)
    op.create_table('user_role_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'FARMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role_once')
    )
    op.create_index('ix_role_assignment_role', 'user_role_assignment', ['role'], unique=False)
    op.create_index(op.f('ix_user_role_assignment_user_id'), 'user_role_assignment', ['user_id'], unique=False)
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('mandal', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_source', sa.String(length=60), nullable=False),
    sa.Column('geocode_accuracy_m', sa.Float(), nullable=True),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('nearest_mandi_name', sa.String(length=120), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude is null or (latitude >= -90 and latitude <= 90)', name='ck_farm_lat_range'),
    sa.CheckConstraint('longitude is null or (longitude >= -180 and longitude <= 180)', name='ck_farm_lon_range'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farm_district_mandal', 'farm', ['district', 'mandal'], unique=False)
    op.create_index(op.f('ix_farm_farmer_id'), 'farm', ['farmer_id'], unique=False)
    op.create_index('ix_farm_geo', 'farm', ['latitude', 'longitude'], unique=False)
    op.create_table('voice_introduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'TE', name='language_pref'), nullable=False),
    sa.Column('transcript_en', sa.Text(), nullable=False),
    sa.Column('transcript_te', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_farmer_active', 'voice_introduction', ['farmer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_voice_introduction_farmer_id'), 'voice_introduction', ['farmer_id'], unique=False)
    op.create_table('crop_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('crop_name_en', sa.String(length=120), nullable=False),
    sa.Column('crop_name_te', sa.String(length=120), nullable=False),
    sa.Column('crop_slug', sa.String(length=120), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_te', sa.Text(), nullable=False),
    sa.Column('quantity_total', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'QUINTAL', 'TONNE', 'DOZEN', 'BUNDLE', 'CRATE', 'PIECE', name='quantity_unit'), nullable=False),
    sa.Column('min_order_quantity', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mandi_reference_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mandi_reference_name', sa.String(length=120), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_until', sa.Date(), nullable=True),
    sa.Column('offers_delivery', sa.Boolean(), nullable=False),
    sa.Column('delivery_radius_km', sa.Float(), nullable=False),
    sa.Column('offers_pickup', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LIVE', 'RESERVED', 'SOLD_OUT', 'UNPUBLISHED', 'EXPIRED', name='listing_status'), nullable=False),
    sa.Column('has_same_day_proof', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('interest_count', sa.Integer(), nullable=False),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_per_unit > 0', name='ck_listing_price_positive'),
    sa.CheckConstraint('quantity_available >= 0', name='ck_listing_qty_nonneg'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_listing_farm_id'), 'crop_listing', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_listing_farmer_id'), 'crop_listing', ['farmer_id'], unique=False)
    op.create_index('ix_listing_crop_slug', 'crop_listing', ['crop_slug'], unique=False)
    op.create_index('ix_listing_farmer_status', 'crop_listing', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_listing_status_harvest', 'crop_listing', ['status', 'harvest_date'], unique=False)
    op.create_table('crop_photo_proof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_date', sa.Date(), nullable=True),
    sa.Column('capture_latitude', sa.Float(), nullable=True),
    sa.Column('capture_longitude', sa.Float(), nullable=True),
    sa.Column('capture_source', sa.String(length=40), nullable=False),
    sa.Column('is_same_day', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('caption_en', sa.String(length=255), nullable=False),
    sa.Column('caption_te', sa.String(length=255), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proof_review_status'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_photo_proof_listing_id'), 'crop_photo_proof', ['listing_id'], unique=False)
    op.create_index('ix_proof_listing_captured', 'crop_photo_proof', ['listing_id', 'captured_at'], unique=False)
    op.create_index('ix_proof_review', 'crop_photo_proof', ['review_status'], unique=False)
    op.create_table('order_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=24), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'QUINTAL', 'TONNE', 'DOZEN', 'BUNDLE', 'CRATE', 'PIECE', name='quantity_unit'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fulfilment_mode', sa.Enum('FARM_PICKUP', 'LOCAL_DELIVERY', name='fulfilment_mode'), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'DECLINED', 'PAID', 'OUT_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='order_status'), nullable=False),
    sa.Column('buyer_note', sa.Text(), nullable=False),
    sa.Column('farmer_note', sa.Text(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_qty_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_nonneg'),
    sa.ForeignKeyConstraint(['buyer_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listing.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code', name='uq_order_code')
    )
    op.create_index('ix_order_buyer_status', 'order_request', ['buyer_id', 'status'], unique=False)
    op.create_index('ix_order_farmer_status', 'order_request', ['farmer_id', 'status'], unique=False)
    op.create_index(op.f('ix_order_request_buyer_id'), 'order_request', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_order_request_farmer_id'), 'order_request', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_order_request_listing_id'), 'order_request', ['listing_id'], unique=False)
    op.create_index(op.f('ix_order_request_order_code'), 'order_request', ['order_code'], unique=False)
    op.create_index('ix_order_status_created', 'order_request', ['status', 'created_at'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listing.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_conversation_order')
    )
    op.create_index('ix_conversation_last_message', 'conversation', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversation_listing_id'), 'conversation', ['listing_id'], unique=False)
    op.create_index(op.f('ix_conversation_order_id'), 'conversation', ['order_id'], unique=False)
    op.create_table('delivery_confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_role', sa.Enum('CUSTOMER', 'FARMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_quantity', sa.Float(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('remarks_en', sa.Text(), nullable=False),
    sa.Column('remarks_te', sa.Text(), nullable=False),
    sa.Column('proof_file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'confirmed_by_role', name='uq_confirm_once')
    )
    op.create_index('ix_confirmation_order', 'delivery_confirmation', ['order_id', 'confirmed_at'], unique=False)
    op.create_index(op.f('ix_delivery_confirmation_order_id'), 'delivery_confirmation', ['order_id'], unique=False)
    op.create_table('delivery_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('mandal', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('slot_label_en', sa.String(length=80), nullable=False),
    sa.Column('slot_label_te', sa.String(length=80), nullable=False),
    sa.Column('instructions_en', sa.Text(), nullable=False),
    sa.Column('instructions_te', sa.Text(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_delivery_detail_order')
    )
    op.create_index(op.f('ix_delivery_detail_order_id'), 'delivery_detail', ['order_id'], unique=False)
    op.create_index('ix_delivery_slot', 'delivery_detail', ['scheduled_date'], unique=False)
    op.create_table('dispute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('raised_by_id', sa.Integer(), nullable=True),
    sa.Column('raised_by_role', sa.Enum('CUSTOMER', 'FARMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('subject_en', sa.String(length=160), nullable=False),
    sa.Column('subject_te', sa.String(length=160), nullable=False),
    sa.Column('details_en', sa.Text(), nullable=False),
    sa.Column('details_te', sa.Text(), nullable=False),
    sa.Column('evidence_file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED_BUYER', 'RESOLVED_FARMER', 'WITHDRAWN', name='dispute_status'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_order', 'dispute', ['order_id'], unique=False)
    op.create_index(op.f('ix_dispute_order_id'), 'dispute', ['order_id'], unique=False)
    op.create_index('ix_dispute_status_created', 'dispute', ['status', 'created_at'], unique=False)
    op.create_table('farmer_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DUE', 'SCHEDULED', 'PAID', 'ON_HOLD', 'FAILED', name='payout_status'), nullable=False),
    sa.Column('method_note', sa.String(length=120), nullable=False),
    sa.Column('payout_reference', sa.String(length=120), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gross_amount >= 0', name='ck_payout_gross_nonneg'),
    sa.CheckConstraint('net_amount >= 0', name='ck_payout_net_nonneg'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_payout_farmer_id'), 'farmer_payout', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_payout_order_id'), 'farmer_payout', ['order_id'], unique=False)
    op.create_index('ix_payout_farmer_status', 'farmer_payout', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_payout_status_created', 'farmer_payout', ['status', 'created_at'], unique=False)
    op.create_table('payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ATTEMPTED', 'CAPTURED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('is_platform_held', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=False),
    sa.Column('receipt_note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['order_id'], ['order_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id', name='uq_payment_rzp_order'),
    sa.UniqueConstraint('razorpay_payment_id', name='uq_payment_rzp_payment')
    )
    op.create_index(op.f('ix_payment_record_order_id'), 'payment_record', ['order_id'], unique=False)
    op.create_index('ix_payment_status_created', 'payment_record', ['status', 'created_at'], unique=False)
    op.create_table('conversation_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_thread', sa.Enum('CUSTOMER', 'FARMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_participant_once')
    )
    op.create_index(op.f('ix_conversation_participant_conversation_id'), 'conversation_participant', ['conversation_id'], unique=False)
    op.create_index('ix_participant_user', 'conversation_participant', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('TEXT', 'VOICE_NOTE', 'SYSTEM', name='message_kind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_language', sa.Enum('EN', 'TE', name='language_pref'), nullable=False),
    sa.Column('voice_file_name', sa.String(length=255), nullable=False),
    sa.Column('voice_duration_seconds', sa.Float(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index('ix_message_conversation_sent', 'message', ['conversation_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_conversation_sent', table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index('ix_participant_user', table_name='conversation_participant')
    op.drop_index(op.f('ix_conversation_participant_conversation_id'), table_name='conversation_participant')
    op.drop_table('conversation_participant')
    op.drop_index('ix_payment_status_created', table_name='payment_record')
    op.drop_index(op.f('ix_payment_record_order_id'), table_name='payment_record')
    op.drop_table('payment_record')
    op.drop_index('ix_payout_status_created', table_name='farmer_payout')
    op.drop_index('ix_payout_farmer_status', table_name='farmer_payout')
    op.drop_index(op.f('ix_farmer_payout_order_id'), table_name='farmer_payout')
    op.drop_index(op.f('ix_farmer_payout_farmer_id'), table_name='farmer_payout')
    op.drop_table('farmer_payout')
    op.drop_index('ix_dispute_status_created', table_name='dispute')
    op.drop_index(op.f('ix_dispute_order_id'), table_name='dispute')
    op.drop_index('ix_dispute_order', table_name='dispute')
    op.drop_table('dispute')
    op.drop_index('ix_delivery_slot', table_name='delivery_detail')
    op.drop_index(op.f('ix_delivery_detail_order_id'), table_name='delivery_detail')
    op.drop_table('delivery_detail')
    op.drop_index(op.f('ix_delivery_confirmation_order_id'), table_name='delivery_confirmation')
    op.drop_index('ix_confirmation_order', table_name='delivery_confirmation')
    op.drop_table('delivery_confirmation')
    op.drop_index(op.f('ix_conversation_order_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_listing_id'), table_name='conversation')
    op.drop_index('ix_conversation_last_message', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('ix_order_status_created', table_name='order_request')
    op.drop_index(op.f('ix_order_request_order_code'), table_name='order_request')
    op.drop_index(op.f('ix_order_request_listing_id'), table_name='order_request')
    op.drop_index(op.f('ix_order_request_farmer_id'), table_name='order_request')
    op.drop_index(op.f('ix_order_request_buyer_id'), table_name='order_request')
    op.drop_index('ix_order_farmer_status', table_name='order_request')
    op.drop_index('ix_order_buyer_status', table_name='order_request')
    op.drop_table('order_request')
    op.drop_index('ix_proof_review', table_name='crop_photo_proof')
    op.drop_index('ix_proof_listing_captured', table_name='crop_photo_proof')
    op.drop_index(op.f('ix_crop_photo_proof_listing_id'), table_name='crop_photo_proof')
    op.drop_table('crop_photo_proof')
    op.drop_index('ix_listing_status_harvest', table_name='crop_listing')
    op.drop_index('ix_listing_farmer_status', table_name='crop_listing')
    op.drop_index('ix_listing_crop_slug', table_name='crop_listing')
    op.drop_index(op.f('ix_crop_listing_farmer_id'), table_name='crop_listing')
    op.drop_index(op.f('ix_crop_listing_farm_id'), table_name='crop_listing')
    op.drop_table('crop_listing')
    op.drop_index(op.f('ix_voice_introduction_farmer_id'), table_name='voice_introduction')
    op.drop_index('ix_voice_farmer_active', table_name='voice_introduction')
    op.drop_table('voice_introduction')
    op.drop_index('ix_farm_geo', table_name='farm')
    op.drop_index(op.f('ix_farm_farmer_id'), table_name='farm')
    op.drop_index('ix_farm_district_mandal', table_name='farm')
    op.drop_table('farm')
    op.drop_index(op.f('ix_user_role_assignment_user_id'), table_name='user_role_assignment')
    op.drop_index('ix_role_assignment_role', table_name='user_role_assignment')
    op.drop_table('user_role_assignment')
    op.drop_index('ix_mandi_district', table_name='mandi_price')
    op.drop_index('ix_mandi_crop_date', table_name='mandi_price')
    op.drop_table('mandi_price')
    op.drop_index('ix_farmer_verification', table_name='farmer_profile')
    op.drop_index(op.f('ix_farmer_profile_user_id'), table_name='farmer_profile')
    op.drop_table('farmer_profile')
    op.drop_index('ix_advisory_published', table_name='advisory_entry')
    op.drop_index(op.f('ix_advisory_entry_slug'), table_name='advisory_entry')
    op.drop_index('ix_advisory_crop_season', table_name='advisory_entry')
    op.drop_table('advisory_entry')
    op.drop_index('ix_audit_entity', table_name='admin_audit_log')
    op.drop_index('ix_audit_actor_created', table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index('ix_user_role_active', table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
